// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iot-synergy/openned8-rpc/ent/industryinfo"
)

// IndustryInfoCreate is the builder for creating a IndustryInfo entity.
type IndustryInfoCreate struct {
	config
	mutation *IndustryInfoMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (iic *IndustryInfoCreate) SetCreatedAt(t time.Time) *IndustryInfoCreate {
	iic.mutation.SetCreatedAt(t)
	return iic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iic *IndustryInfoCreate) SetNillableCreatedAt(t *time.Time) *IndustryInfoCreate {
	if t != nil {
		iic.SetCreatedAt(*t)
	}
	return iic
}

// SetUpdatedAt sets the "updated_at" field.
func (iic *IndustryInfoCreate) SetUpdatedAt(t time.Time) *IndustryInfoCreate {
	iic.mutation.SetUpdatedAt(t)
	return iic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (iic *IndustryInfoCreate) SetNillableUpdatedAt(t *time.Time) *IndustryInfoCreate {
	if t != nil {
		iic.SetUpdatedAt(*t)
	}
	return iic
}

// SetName sets the "name" field.
func (iic *IndustryInfoCreate) SetName(s string) *IndustryInfoCreate {
	iic.mutation.SetName(s)
	return iic
}

// SetID sets the "id" field.
func (iic *IndustryInfoCreate) SetID(u uint64) *IndustryInfoCreate {
	iic.mutation.SetID(u)
	return iic
}

// Mutation returns the IndustryInfoMutation object of the builder.
func (iic *IndustryInfoCreate) Mutation() *IndustryInfoMutation {
	return iic.mutation
}

// Save creates the IndustryInfo in the database.
func (iic *IndustryInfoCreate) Save(ctx context.Context) (*IndustryInfo, error) {
	iic.defaults()
	return withHooks(ctx, iic.sqlSave, iic.mutation, iic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iic *IndustryInfoCreate) SaveX(ctx context.Context) *IndustryInfo {
	v, err := iic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iic *IndustryInfoCreate) Exec(ctx context.Context) error {
	_, err := iic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iic *IndustryInfoCreate) ExecX(ctx context.Context) {
	if err := iic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iic *IndustryInfoCreate) defaults() {
	if _, ok := iic.mutation.CreatedAt(); !ok {
		v := industryinfo.DefaultCreatedAt()
		iic.mutation.SetCreatedAt(v)
	}
	if _, ok := iic.mutation.UpdatedAt(); !ok {
		v := industryinfo.DefaultUpdatedAt()
		iic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iic *IndustryInfoCreate) check() error {
	if _, ok := iic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IndustryInfo.created_at"`)}
	}
	if _, ok := iic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IndustryInfo.updated_at"`)}
	}
	if _, ok := iic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IndustryInfo.name"`)}
	}
	return nil
}

func (iic *IndustryInfoCreate) sqlSave(ctx context.Context) (*IndustryInfo, error) {
	if err := iic.check(); err != nil {
		return nil, err
	}
	_node, _spec := iic.createSpec()
	if err := sqlgraph.CreateNode(ctx, iic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	iic.mutation.id = &_node.ID
	iic.mutation.done = true
	return _node, nil
}

func (iic *IndustryInfoCreate) createSpec() (*IndustryInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &IndustryInfo{config: iic.config}
		_spec = sqlgraph.NewCreateSpec(industryinfo.Table, sqlgraph.NewFieldSpec(industryinfo.FieldID, field.TypeUint64))
	)
	if id, ok := iic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := iic.mutation.CreatedAt(); ok {
		_spec.SetField(industryinfo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := iic.mutation.UpdatedAt(); ok {
		_spec.SetField(industryinfo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := iic.mutation.Name(); ok {
		_spec.SetField(industryinfo.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// IndustryInfoCreateBulk is the builder for creating many IndustryInfo entities in bulk.
type IndustryInfoCreateBulk struct {
	config
	err      error
	builders []*IndustryInfoCreate
}

// Save creates the IndustryInfo entities in the database.
func (iicb *IndustryInfoCreateBulk) Save(ctx context.Context) ([]*IndustryInfo, error) {
	if iicb.err != nil {
		return nil, iicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iicb.builders))
	nodes := make([]*IndustryInfo, len(iicb.builders))
	mutators := make([]Mutator, len(iicb.builders))
	for i := range iicb.builders {
		func(i int, root context.Context) {
			builder := iicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndustryInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iicb *IndustryInfoCreateBulk) SaveX(ctx context.Context) []*IndustryInfo {
	v, err := iicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iicb *IndustryInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := iicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iicb *IndustryInfoCreateBulk) ExecX(ctx context.Context) {
	if err := iicb.Exec(ctx); err != nil {
		panic(err)
	}
}
