// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iot-synergy/openned8-rpc/ent/industryinfo"
	"github.com/iot-synergy/openned8-rpc/ent/predicate"
)

// IndustryInfoDelete is the builder for deleting a IndustryInfo entity.
type IndustryInfoDelete struct {
	config
	hooks    []Hook
	mutation *IndustryInfoMutation
}

// Where appends a list predicates to the IndustryInfoDelete builder.
func (iid *IndustryInfoDelete) Where(ps ...predicate.IndustryInfo) *IndustryInfoDelete {
	iid.mutation.Where(ps...)
	return iid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iid *IndustryInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, iid.sqlExec, iid.mutation, iid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (iid *IndustryInfoDelete) ExecX(ctx context.Context) int {
	n, err := iid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iid *IndustryInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(industryinfo.Table, sqlgraph.NewFieldSpec(industryinfo.FieldID, field.TypeUint64))
	if ps := iid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	iid.mutation.done = true
	return affected, err
}

// IndustryInfoDeleteOne is the builder for deleting a single IndustryInfo entity.
type IndustryInfoDeleteOne struct {
	iid *IndustryInfoDelete
}

// Where appends a list predicates to the IndustryInfoDelete builder.
func (iido *IndustryInfoDeleteOne) Where(ps ...predicate.IndustryInfo) *IndustryInfoDeleteOne {
	iido.iid.mutation.Where(ps...)
	return iido
}

// Exec executes the deletion query.
func (iido *IndustryInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := iido.iid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{industryinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iido *IndustryInfoDeleteOne) ExecX(ctx context.Context) {
	if err := iido.Exec(ctx); err != nil {
		panic(err)
	}
}
