// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iot-synergy/openned8-rpc/ent/predicate"
	"github.com/iot-synergy/openned8-rpc/ent/sdkusage"
)

// SdkUsageDelete is the builder for deleting a SdkUsage entity.
type SdkUsageDelete struct {
	config
	hooks    []Hook
	mutation *SdkUsageMutation
}

// Where appends a list predicates to the SdkUsageDelete builder.
func (sud *SdkUsageDelete) Where(ps ...predicate.SdkUsage) *SdkUsageDelete {
	sud.mutation.Where(ps...)
	return sud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sud *SdkUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sud.sqlExec, sud.mutation, sud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sud *SdkUsageDelete) ExecX(ctx context.Context) int {
	n, err := sud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sud *SdkUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sdkusage.Table, sqlgraph.NewFieldSpec(sdkusage.FieldID, field.TypeUUID))
	if ps := sud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sud.mutation.done = true
	return affected, err
}

// SdkUsageDeleteOne is the builder for deleting a single SdkUsage entity.
type SdkUsageDeleteOne struct {
	sud *SdkUsageDelete
}

// Where appends a list predicates to the SdkUsageDelete builder.
func (sudo *SdkUsageDeleteOne) Where(ps ...predicate.SdkUsage) *SdkUsageDeleteOne {
	sudo.sud.mutation.Where(ps...)
	return sudo
}

// Exec executes the deletion query.
func (sudo *SdkUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := sudo.sud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sdkusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sudo *SdkUsageDeleteOne) ExecX(ctx context.Context) {
	if err := sudo.Exec(ctx); err != nil {
		panic(err)
	}
}
